### ISSUE TITLE
Embedded Translations

### ISSUE THREAD

**Issue by ltouro** [Azure-Samples/active-directory-b2c-advanced-policies#22]
Does the final policies support language customizations (enable/disable languagues, set the default language)? And what about customized resources for each language? 

These are features from the simpler Azure B2C UI Customization that I would need in order to switch to advanced policies.

Thanks for these resources. Very usefull.

**Comment by chrispadgettlivecom** [comment]
Hi @ltouro 

You can find information about language customization for custom policies at ["Language customization in custom policies"](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-language-customization-custom).

[The base file](https://github.com/Azure-Samples/active-directory-b2c-advanced-policies/blob/master/wingtipgamesb2c/Policies/b2ctechready.onmicrosoft.com_B2C_1A_base.xml) for [the Wingtip sample](https://github.com/Azure-Samples/active-directory-b2c-advanced-policies/tree/master/wingtipgamesb2c) contains an example of language customization for English and French.

**Comment by ltouro** [comment]
Thanks @chrispadgettlivecom , it worked.
