### ISSUE TITLE
Keep me signed in (KMSI) experience 

### ISSUE THREAD

**Issue by ltouro** [Azure-Samples/active-directory-b2c-advanced-policies#23]
I was able to enable KMSI experience by using the UserJourneyBehaviors XML node. The Sign-in Or Sign-Up policy already shows the button "Keep me signed in?".

Notwithstanding, by acessing the URL for Login again (i.e. Run Now), the user is still redirect to the login page. Should'nt the user be redirect to the final page after checking KMSI option the first time?

Otherwise, how can I test the KMSI experience?

Thanks once more for these wonderful resources.

**Comment by chrispadgettlivecom** [comment]
Hi @ltouro 

The "Run Now" link includes the `prompt=login` parameter which forces-reauthentication. You can remove this from the generated link to test the KMSI experience.

**Comment by ltouro** [comment]
@chrispadgettlivecom Thanks once more!

**Comment by kubaizi** [comment]
but how can i localize it ?
i try 
`<LocalizedString ElementType="UxElement" StringId="remember_me">blah blah</LocalizedString>`
but still give me : 

> the localized string with ElementType: UxElement and StringId: remember_me has an invalid StringId

everything else is working

**Comment by kubaizi** [comment]
this is helpful thank you but how can I localize it?
I try 
`<LocalizedString ElementType="UxElement" StringId="remember_me">Kqwqweqwen</LocalizedString>`
but still no luck while everything else is working fine
