### ISSUE TITLE
Documentation part 1 diagram difficult to read

### ISSUE THREAD

**Issue by BlueCloudDev** [Azure-Samples/active-directory-b2c-advanced-policies#7]
Could the diagram in part 1 of the documentation be replaced with a clearer image? Most of the text, especially in the orange blocks is difficult to read.

This piece: https://github.com/Azure-Samples/active-directory-b2c-advanced-policies/blob/master/Documentation/media/01_06.png

If you open it in a completely new tab it's readable, but the issue is that the text is white with a black shadow that gets blurred when resized.

**Comment by rojasja** [comment]
Hi!,
I must have missed your message much earliere.  I've uploaded a better version in PDF of this file named signup protocol attribute flow docs
